In [36]:
import pandas as pd
import numpy as np

In [37]:
leagues = ['9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920', '2021', '2122', '2223', '2324', '2425']

In [38]:
master_df = pd.DataFrame()

for league in leagues:
    league_df = pd.read_csv(f"data/season-{league}.csv")
    master_df = pd.concat([master_df, league_df], axis=0)

print(master_df)

         Date    HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  HTR  \
0    05/09/93  Ath Bilbao     Albacete     4     1   H   NaN   NaN  NaN
1    05/09/93  Ath Madrid     Logrones     1     0   H   NaN   NaN  NaN
2    05/09/93   Barcelona     Sociedad     3     0   H   NaN   NaN  NaN
3    05/09/93   La Coruna        Celta     0     0   D   NaN   NaN  NaN
4    05/09/93     Osasuna  Real Madrid     1     4   A   NaN   NaN  NaN
..        ...         ...          ...   ...   ...  ..   ...   ...  ...
273  16/03/25     Leganes        Betis     2     3   A   2.0   0.0    H
274  16/03/25     Sevilla   Ath Bilbao     0     1   A   0.0   0.0    D
275  16/03/25     Osasuna       Getafe     1     2   A   1.0   0.0    H
276  16/03/25   Vallecano     Sociedad     2     2   D   0.0   1.0    A
277  16/03/25  Ath Madrid    Barcelona     2     4   A   1.0   0.0    H

     Referee  ...  HST  AST    HF    AF   HC   AC   HY   AY   HR   AR
0        NaN  ...  NaN  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN
1        NaN  ...  NaN  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN
2        NaN  ...  NaN  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN
3        NaN  ...  NaN  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN
4        NaN  ...  NaN  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN
..       ...  ...  ...  ...   ...   ...  ...  ...  ...  ...  ...  ...
273      NaN  ...  4.0  6.0  16.0   5.0  3.0  7.0  2.0  1.0  0.0  0.0
274      NaN  ...  4.0  4.0  13.0  12.0  4.0  6.0  4.0  2.0  0.0  0.0
275      NaN  ...  4.0  4.0  19.0  15.0  3.0  2.0  2.0  3.0  0.0  1.0
276      NaN  ...  5.0  4.0  16.0   9.0  4.0  4.0  3.0  2.0  0.0  0.0
277      NaN  ...  2.0  6.0  10.0  11.0  6.0  6.0  1.0  3.0  0.0  0.0

[12222 rows x 22 columns]

In [39]:
print(master_df.columns)

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR'],
      dtype='object')

In [45]:
referee_DF = master_df['Date_ddmmyy'].to_frame()

referee_DF

    Date_ddmmyy
0      05/09/93
1      05/09/93
2      05/09/93
3      05/09/93
4      05/09/93
..          ...
273    16/03/25
274    16/03/25
275    16/03/25
276    16/03/25
277    16/03/25

[12222 rows x 1 columns]

In [43]:
columns = ['Date_ddmmyy', 'H_Team', 'A_Team', 'Full_Time_H_Goals', 'Full_Time_A_Goals', 'Full_Time_Result', 'Half_Time_H_Goals', 'Half_Time_A_Goals',
       'Half_Time_Result', 'Referee', 'H_Shots', 'A_Shots', 'H_Shots_on_Target', 'A_Shots_on_Target', 'H_Fouls', 'A_Fouls', 'H_Corners', 'A_Corners',
       'H_Yellow', 'A_Yellow', 'H_Red', 'A_Red']

In [44]:
master_df.columns = columns

In [46]:
master_df

,Date_ddmmyy,H_Team,A_Team,Full_Time_H_Goals,Full_Time_A_Goals,Full_Time_Result,Half_Time_H_Goals,Half_Time_A_Goals,Half_Time_Result,Referee,...,H_Shots_on_Target,A_Shots_on_Target,H_Fouls,A_Fouls,H_Corners,A_Corners,H_Yellow,A_Yellow,H_Red,A_Red
0,05/09/93,Ath Bilbao,Albacete,4,1,H,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,05/09/93,Ath Madrid,Logrones,1,0,H,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,05/09/93,Barcelona,Sociedad,3,0,H,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,05/09/93,La Coruna,Celta,0,0,D,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,05/09/93,Osasuna,Real Madrid,1,4,A,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,16/03/25,Leganes,Betis,2,3,A,2.0,0.0,H,NaN,...,4.0,6.0,16.0,5.0,3.0,7.0,2.0,1.0,0.0,0.0
274,16/03/25,Sevilla,Ath Bilbao,0,1,A,0.0,0.0,D,NaN,...,4.0,4.0,13.0,12.0,4.0,6.0,4.0,2.0,0.0,0.0
275,16/03/25,Osasuna,Getafe,1,2,A,1.0,0.0,H,NaN,...,4.0,4.0,19.0,15.0,3.0,2.0,2.0,3.0,0.0,1.0
276,16/03/25,Vallecano,Sociedad,2,2,D,0.0,1.0,A,NaN,...,5.0,4.0,16.0,9.0,4.0,4.0,3.0,2.0,0.0,0.0
277,16/03/25,Ath Madrid,Barcelona,2,4,A,1.0,0.0,H,NaN,...,2.0,6.0,10.0,11.0,6.0,6.0,1.0,3.0,0.0,0.0

In [47]:
master_df.to_csv('output.csv', index=False)

In [48]:
master_df['Date_ddmmyy'] = pd.to_datetime(master_df['Date_ddmmyy'], format='%d/%m/%y')
master_df

,Date_ddmmyy,H_Team,A_Team,Full_Time_H_Goals,Full_Time_A_Goals,Full_Time_Result,Half_Time_H_Goals,Half_Time_A_Goals,Half_Time_Result,Referee,...,H_Shots_on_Target,A_Shots_on_Target,H_Fouls,A_Fouls,H_Corners,A_Corners,H_Yellow,A_Yellow,H_Red,A_Red
0,1993-09-05,Ath Bilbao,Albacete,4,1,H,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1993-09-05,Ath Madrid,Logrones,1,0,H,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1993-09-05,Barcelona,Sociedad,3,0,H,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1993-09-05,La Coruna,Celta,0,0,D,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1993-09-05,Osasuna,Real Madrid,1,4,A,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,2025-03-16,Leganes,Betis,2,3,A,2.0,0.0,H,NaN,...,4.0,6.0,16.0,5.0,3.0,7.0,2.0,1.0,0.0,0.0
274,2025-03-16,Sevilla,Ath Bilbao,0,1,A,0.0,0.0,D,NaN,...,4.0,4.0,13.0,12.0,4.0,6.0,4.0,2.0,0.0,0.0
275,2025-03-16,Osasuna,Getafe,1,2,A,1.0,0.0,H,NaN,...,4.0,4.0,19.0,15.0,3.0,2.0,2.0,3.0,0.0,1.0
276,2025-03-16,Vallecano,Sociedad,2,2,D,0.0,1.0,A,NaN,...,5.0,4.0,16.0,9.0,4.0,4.0,3.0,2.0,0.0,0.0
277,2025-03-16,Ath Madrid,Barcelona,2,4,A,1.0,0.0,H,NaN,...,2.0,6.0,10.0,11.0,6.0,6.0,1.0,3.0,0.0,0.0

In [49]:
teams = master_df['H_Team'].unique().tolist()
print(teams, len(teams))

['Ath Bilbao', 'Ath Madrid', 'Barcelona', 'La Coruna', 'Osasuna', 'Oviedo', 'Santander', 'Tenerife', 'Valladolid', 'Zaragoza', 'Albacete', 'Celta', 'Lerida', 'Logrones', 'Real Madrid', 'Sevilla', 'Sociedad', 'Sp Gijon', 'Valencia', 'Vallecano', 'Compostela', 'Espanol', 'Betis', 'Merida', 'Salamanca', 'Hercules', 'Extremadura', 'Mallorca', 'Alaves', 'Villareal', 'Malaga', 'Numancia', 'Las Palmas', 'Villarreal', 'Recreativo', 'Murcia', 'Getafe', 'Levante', 'Cadiz', 'Gimnastic', 'Almeria', 'Xerez', 'Granada', 'Elche', 'Eibar', 'Cordoba', 'Leganes', 'Girona', 'Huesca'] 49

In [58]:
grouped = master_df.groupby('H_Team')
H_splits_dfs = {category: group for category, group in grouped}
grouped = master_df.groupby('A_Team')
A_splits_dfs = {category: group for category, group in grouped}

for team in teams:
    home_df = H_splits_dfs[team]
    away_df = A_splits_dfs[team]

    combined_df = pd.concat([home_df, away_df], axis=0)
    sorted_combined_df = combined_df.sort_values(by='Date_ddmmyy')
    sorted_combined_df.to_csv(f'{team}.csv', index=False)
    print(team)

Ath Bilbao
Ath Madrid
Barcelona
La Coruna
Osasuna
Oviedo
Santander
Tenerife
Valladolid
Zaragoza
Albacete
Celta
Lerida
Logrones
Real Madrid
Sevilla
Sociedad
Sp Gijon
Valencia
Vallecano
Compostela
Espanol
Betis
Merida
Salamanca
Hercules
Extremadura
Mallorca
Alaves
Villareal
Malaga
Numancia
Las Palmas
Villarreal
Recreativo
Murcia
Getafe
Levante
Cadiz
Gimnastic
Almeria
Xerez
Granada
Elche
Eibar
Cordoba
Leganes
Girona
Huesca

{'Alaves':     Date_ddmmyy  H_Team       A_Team  Full_Time_H_Goals  Full_Time_A_Goals  \
 0    1998-08-29  Alaves        Betis                  0                  0
 21   1998-09-20  Alaves     Zaragoza                  1                  0
 41   1998-10-04  Alaves    Santander                  0                  1
 61   1998-10-25  Alaves  Extremadura                  0                  1
 81   1998-11-08  Alaves  Real Madrid                  1                  1
 ..          ...     ...          ...                ...                ...
 183  2025-01-11  Alaves       Girona                  0                  1
 209  2025-01-27  Alaves        Celta                  1                  1
 225  2025-02-09  Alaves       Getafe                  0                  1
 241  2025-02-22  Alaves      Espanol                  0                  1
 260  2025-03-08  Alaves   Villarreal                  1                  0

     Full_Time_Result  Half_Time_H_Goals  Half_Time_A_Goals Half_Time_Result  \
 0                  D                0.0                0.0                D
 21                 H                0.0                0.0                D
 41                 A                0.0                1.0                A
 61                 A                0.0                1.0                A
 81                 D                1.0                0.0                H
 ..               ...                ...                ...              ...
 183                A                0.0                0.0                D
 209                D                1.0                0.0                H
 225                A                0.0                1.0                A
 241                A                0.0                0.0                D
 260                H                1.0                0.0                H

      Referee  ...  H_Shots_on_Target  A_Shots_on_Target  H_Fouls  A_Fouls  \
 0        NaN  ...                NaN                NaN      NaN      NaN
 21       NaN  ...                NaN                NaN      NaN      NaN
 41       NaN  ...                NaN                NaN      NaN      NaN
 61       NaN  ...                NaN                NaN      NaN      NaN
 81       NaN  ...                NaN                NaN      NaN      NaN
 ..       ...  ...                ...                ...      ...      ...
 183      NaN  ...                2.0                1.0     16.0     11.0
 209      NaN  ...                1.0                2.0     15.0     14.0
 225      NaN  ...                4.0                3.0     16.0     16.0
 241      NaN  ...                5.0                2.0     13.0     17.0
 260      NaN  ...                3.0                2.0     11.0     13.0

      H_Corners  A_Corners  H_Yellow  A_Yellow  H_Red  A_Red
 0          NaN        NaN       NaN       NaN    NaN    NaN
 21         NaN        NaN       NaN       NaN    NaN    NaN
 41         NaN        NaN       NaN       NaN    NaN    NaN
 61         NaN        NaN       NaN       NaN    NaN    NaN
 81         NaN        NaN       NaN       NaN    NaN    NaN
 ..         ...        ...       ...       ...    ...    ...
 183        6.0        3.0       1.0       4.0    0.0    0.0
 209        3.0        4.0       2.0       3.0    0.0    0.0
 225        8.0        3.0       2.0       6.0    0.0    0.0
 241        7.0        0.0       2.0       2.0    0.0    0.0
 260        1.0        6.0       3.0       1.0    2.0    0.0

 [260 rows x 22 columns],
 'Albacete':     Date_ddmmyy    H_Team       A_Team  Full_Time_H_Goals  Full_Time_A_Goals  \
 10   1993-09-12  Albacete    Barcelona                  0                  0
 30   1993-09-26  Albacete      Osasuna                  2                  1
 50   1993-10-06  Albacete    La Coruna                  0                  0
 70   1993-10-24  Albacete   Ath Madrid                  2                  2
 90   1993-11-07  Albacete     Tenerife                  2                  3
 ..          ...       ...          ...                ...                ...
 271  2005-03-13  Albacete    La Coruna                  0                  1
 292  2005-04-03  Albacete  Real Madrid                  1                  2
 312  2005-04-17  Albacete       Malaga                  1                  2
 344  2005-05-08  Albacete      Levante                  3                  1
 362  2005-05-22  Albacete     Sociedad                  2                  2

     Full_Time_Result  Half_Time_H_Goals  Half_Time_A_Goals Half_Time_Result  \
 10                 D                NaN                NaN              NaN
 30                 H                NaN                NaN              NaN
 50                 D                NaN                NaN              NaN
 70                 D                NaN                NaN              NaN
 90                 A                NaN                NaN              NaN
 ..               ...                ...                ...              ...
 271                A                0.0                1.0                A
 292                A                1.0                2.0                A
 312                A                0.0                0.0                D
 344                H                1.0                0.0                H
 362                D                2.0                0.0                H

      Referee  ...  H_Shots_on_Target  A_Shots_on_Target  H_Fouls  A_Fouls  \
 10       NaN  ...                NaN                NaN      NaN      NaN
 30       NaN  ...                NaN                NaN      NaN      NaN
 50       NaN  ...                NaN                NaN      NaN      NaN
 70       NaN  ...                NaN                NaN      NaN      NaN
 90       NaN  ...                NaN                NaN      NaN      NaN
 ..       ...  ...                ...                ...      ...      ...
 271      NaN  ...                NaN                NaN      NaN      NaN
 292      NaN  ...                NaN                NaN      NaN      NaN
 312      NaN  ...                NaN                NaN      NaN      NaN
 344      NaN  ...                NaN                NaN      NaN      NaN
 362      NaN  ...                NaN                NaN      NaN      NaN

      H_Corners  A_Corners  H_Yellow  A_Yellow  H_Red  A_Red
 10         NaN        NaN       NaN       NaN    NaN    NaN
 30         NaN        NaN       NaN       NaN    NaN    NaN
 50         NaN        NaN       NaN       NaN    NaN    NaN
 70         NaN        NaN       NaN       NaN    NaN    NaN
 90         NaN        NaN       NaN       NaN    NaN    NaN
 ..         ...        ...       ...       ...    ...    ...
 271        NaN        NaN       NaN       NaN    NaN    NaN
 292        NaN        NaN       NaN       NaN    NaN    NaN
 312        NaN        NaN       NaN       NaN    NaN    NaN
 344        NaN        NaN       NaN       NaN    NaN    NaN
 362        NaN        NaN       NaN       NaN    NaN    NaN

 [97 rows x 22 columns],
 'Almeria':     Date_ddmmyy   H_Team      A_Team  Full_Time_H_Goals  Full_Time_A_Goals  \
 12   2007-09-02  Almeria    Valencia                  1                  2
 31   2007-09-23  Almeria    Mallorca                  1                  1
 51   2007-09-30  Almeria   Santander                  0                  1
 73   2007-10-21  Almeria     Osasuna                  2                  0
 89   2007-10-31  Almeria    Zaragoza                  0                  1
 ..          ...      ...         ...                ...                ...
 291  2024-03-30  Almeria     Osasuna                  0                  3
 316  2024-04-21  Almeria  Villarreal                  1                  2
 322  2024-04-27  Almeria      Getafe                  1                  3
 358  2024-05-16  Almeria   Barcelona                  0                  2
 373  2024-05-25  Almeria       Cadiz                  6                  1

     Full_Time_Result  Half_Time_H_Goals  Half_Time_A_Goals Half_Time_Result  \
 12                 A                0.0                0.0                D
 31                 D                1.0                0.0                H
 51                 A                0.0                1.0                A
 73                 H                0.0                0.0                D
 89                 A                0.0                0.0                D
 ..               ...                ...                ...              ...
 291                A                0.0                2.0                A
 316                A                1.0                1.0                D
 322                A                1.0                1.0                D
 358                A                0.0                1.0                A
 373                H                0.0                1.0                A

      Referee  ...  H_Shots_on_Target  A_Shots_on_Target  H_Fouls  A_Fouls  \
 12       NaN  ...                4.0                3.0     23.0     22.0
 31       NaN  ...                4.0                7.0     25.0     10.0
 51       NaN  ...                3.0                3.0     12.0     24.0
 73       NaN  ...                5.0                3.0     17.0     11.0
 89       NaN  ...                6.0                4.0     10.0     12.0
 ..       ...  ...                ...                ...      ...      ...
 291      NaN  ...                5.0                4.0     12.0     14.0
 316      NaN  ...                5.0                3.0     10.0     16.0
 322      NaN  ...               11.0                5.0     15.0     31.0
 358      NaN  ...                3.0                7.0      9.0     11.0
 373      NaN  ...               12.0                4.0      4.0      9.0

      H_Corners  A_Corners  H_Yellow  A_Yellow  H_Red  A_Red
 12         5.0        2.0       3.0       2.0    0.0    0.0
 31         9.0        6.0       1.0       1.0    0.0    0.0
 51         4.0        4.0       3.0       1.0    0.0    0.0
 73         6.0        5.0       2.0       2.0    0.0    1.0
 89        10.0        5.0       1.0       4.0    0.0    0.0
 ..         ...        ...       ...       ...    ...    ...
 291        6.0        1.0       3.0       2.0    0.0    0.0
 316        5.0        2.0       3.0       4.0    1.0    0.0
 322        9.0        2.0       5.0       4.0    1.0    0.0
 358        4.0        7.0       0.0       1.0    0.0    0.0
 373        1.0        4.0       2.0       2.0    0.0    0.0

 [152 rows x 22 columns],
 'Ath Bilbao':     Date_ddmmyy      H_Team      A_Team  Full_Time_H_Goals  Full_Time_A_Goals  \
 0    1993-09-05  Ath Bilbao    Albacete                  4                  1
 20   1993-09-19  Ath Bilbao   Barcelona                  0                  0
 40   1993-10-03  Ath Bilbao    Zaragoza                  2                  1
 60   1993-10-17  Ath Bilbao     Osasuna                  1                  2
 80   1993-10-31  Ath Bilbao  Valladolid                  3                  0
 ..          ...         ...         ...                ...                ...
 155  2024-12-08  Ath Bilbao  Villarreal                  2                  0
 207  2025-01-26  Ath Bilbao     Leganes                  0                  0
 222  2025-02-08  Ath Bilbao      Girona                  3                  0
 245  2025-02-23  Ath Bilbao  Valladolid                  7                  1
 264  2025-03-09  Ath Bilbao    Mallorca                  1                  1

     Full_Time_Result  Half_Time_H_Goals  Half_Time_A_Goals Half_Time_Result  \
 0                  H                NaN                NaN              NaN
 20                 D                NaN                NaN              NaN
 40                 H                NaN                NaN              NaN
 60                 A                NaN                NaN              NaN
 80                 H                NaN                NaN              NaN
 ..               ...                ...                ...              ...
 155                H                1.0                0.0                H
 207                D                0.0                0.0                D
 222                H                2.0                0.0                H
 245                H                4.0                0.0                H
 264                D                0.0                0.0                D

      Referee  ...  H_Shots_on_Target  A_Shots_on_Target  H_Fouls  A_Fouls  \
 0        NaN  ...                NaN                NaN      NaN      NaN
 20       NaN  ...                NaN                NaN      NaN      NaN
 40       NaN  ...                NaN                NaN      NaN      NaN
 60       NaN  ...                NaN                NaN      NaN      NaN
 80       NaN  ...                NaN                NaN      NaN      NaN
 ..       ...  ...                ...                ...      ...      ...
 155      NaN  ...                4.0                1.0     15.0     10.0
 207      NaN  ...                3.0                2.0     10.0      8.0
 222      NaN  ...                8.0                1.0      7.0     12.0
 245      NaN  ...               16.0                3.0     10.0      5.0
 264      NaN  ...                2.0                2.0      6.0     13.0

      H_Corners  A_Corners  H_Yellow  A_Yellow  H_Red  A_Red
 0          NaN        NaN       NaN       NaN    NaN    NaN
 20         NaN        NaN       NaN       NaN    NaN    NaN
 40         NaN        NaN       NaN       NaN    NaN    NaN
 60         NaN        NaN       NaN       NaN    NaN    NaN
 80         NaN        NaN       NaN       NaN    NaN    NaN
 ..         ...        ...       ...       ...    ...    ...
 155        3.0        3.0       2.0       1.0    0.0    0.0
 207       16.0        1.0       1.0       1.0    0.0    0.0
 222       11.0        2.0       0.0       4.0    0.0    0.0
 245        4.0        4.0       2.0       3.0    0.0    1.0
 264        3.0        3.0       1.0       3.0    0.0    0.0

 [607 rows x 22 columns],
 'Ath Madrid':     Date_ddmmyy      H_Team       A_Team  Full_Time_H_Goals  \
 1    1993-09-05  Ath Madrid     Logrones                  1
 21   1993-09-19  Ath Madrid        Celta                  3
 41   1993-10-03  Ath Madrid  Real Madrid                  0
 61   1993-10-17  Ath Madrid     Sociedad                  1
 81   1993-10-31  Ath Madrid    Barcelona                  4
 ..          ...         ...          ...                ...
 202  2025-01-25  Ath Madrid   Villarreal                  1
 213  2025-02-01  Ath Madrid     Mallorca                  2
 233  2025-02-15  Ath Madrid        Celta                  1
 254  2025-03-01  Ath Madrid   Ath Bilbao                  1
 277  2025-03-16  Ath Madrid    Barcelona                  2

      Full_Time_A_Goals Full_Time_Result  Half_Time_H_Goals  Half_Time_A_Goals  \
 1                    0                H                NaN                NaN
 21                   2                H                NaN                NaN
 41                   0                D                NaN                NaN
 61                   2                A                NaN                NaN
 81                   3                H                NaN                NaN
 ..                 ...              ...                ...                ...
 202                  1                D                0.0                1.0
 213                  0                H                1.0                0.0
 233                  1                D                0.0                0.0
 254                  0                H                0.0                0.0
 277                  4                A                1.0                0.0

     Half_Time_Result  Referee  ...  H_Shots_on_Target  A_Shots_on_Target  \
 1                NaN      NaN  ...                NaN                NaN
 21               NaN      NaN  ...                NaN                NaN
 41               NaN      NaN  ...                NaN                NaN
 61               NaN      NaN  ...                NaN                NaN
 81               NaN      NaN  ...                NaN                NaN
 ..               ...      ...  ...                ...                ...
 202                A      NaN  ...                8.0                1.0
 213                H      NaN  ...                5.0                1.0
 233                D      NaN  ...                3.0                4.0
 254                D      NaN  ...                4.0                3.0
 277                H      NaN  ...                2.0                6.0

      H_Fouls  A_Fouls  H_Corners  A_Corners  H_Yellow  A_Yellow  H_Red  A_Red
 1        NaN      NaN        NaN        NaN       NaN       NaN    NaN    NaN
 21       NaN      NaN        NaN        NaN       NaN       NaN    NaN    NaN
 41       NaN      NaN        NaN        NaN       NaN       NaN    NaN    NaN
 61       NaN      NaN        NaN        NaN       NaN       NaN    NaN    NaN
 81       NaN      NaN        NaN        NaN       NaN       NaN    NaN    NaN
 ..       ...      ...        ...        ...       ...       ...    ...    ...
 202     10.0     14.0        5.0        6.0       4.0       2.0    0.0    0.0
 213      9.0     14.0       10.0        4.0       2.0       3.0    0.0    0.0
 233      8.0     18.0        2.0        7.0       3.0       5.0    1.0    0.0
 254      7.0      8.0        6.0        2.0       2.0       3.0    0.0    0.0
 277     10.0     11.0        6.0        6.0       1.0       3.0    0.0    0.0

 [570 rows x 22 columns],
 'Barcelona':     Date_ddmmyy     H_Team      A_Team  Full_Time_H_Goals  Full_Time_A_Goals  \
 2    1993-09-05  Barcelona    Sociedad                  3                  0
 31   1993-09-26  Barcelona    Zaragoza                  4                  1
 51   1993-10-06  Barcelona  Valladolid                  3                  0
 71   1993-10-24  Barcelona      Oviedo                  1                  0
 91   1993-11-07  Barcelona   Santander                  2                  1
 ..          ...        ...         ...                ...                ...
 175  2024-12-21  Barcelona  Ath Madrid                  1                  2
 208  2025-01-26  Barcelona    Valencia                  7                  1
 215  2025-02-02  Barcelona      Alaves                  1                  0
 239  2025-02-17  Barcelona   Vallecano                  1                  0
 256  2025-03-02  Barcelona    Sociedad                  4                  0

     Full_Time_Result  Half_Time_H_Goals  Half_Time_A_Goals Half_Time_Result  \
 2                  H                NaN                NaN              NaN
 31                 H                NaN                NaN              NaN
 51                 H                NaN                NaN              NaN
 71                 H                NaN                NaN              NaN
 91                 H                NaN                NaN              NaN
 ..               ...                ...                ...              ...
 175                A                1.0                0.0                H
 208                H                5.0                0.0                H
 215                H                0.0                0.0                D
 239                H                1.0                0.0                H
 256                H                2.0                0.0                H

      Referee  ...  H_Shots_on_Target  A_Shots_on_Target  H_Fouls  A_Fouls  \
 2        NaN  ...                NaN                NaN      NaN      NaN
 31       NaN  ...                NaN                NaN      NaN      NaN
 51       NaN  ...                NaN                NaN      NaN      NaN
 71       NaN  ...                NaN                NaN      NaN      NaN